services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: NODE_OPTIONS="--max-old-space-size=400" npm ci && NODE_OPTIONS="--max-old-space-size=400" npm run build
    startCommand: npm start
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=400
